### ISSUE TITLE
Have one observer for one SingleLiveEvent only

### ISSUE THREAD

**Issue by Taranjot-Singh** [CMPUT301F20T24/Unlibrary#117]
I had encountered some hard to reproduce cases where the app has crashed because the wrong observer observed the changes in the SingleLiveEvent. I think it would be best practice to have only one observer per SingleLiveEvent. This would mean that for cases like the library section where 3 different fragments all observe SingleLiveEvent<NavDirections> mNavigationEvent, we would have 3 different SingleLiveEvents instead.

**Comment by armiantos** [comment]
Is this still valid?

**Comment by calebschoepp** [comment]
We have not been able to reproduce any bugs from this issue. Closing the issue.
