### ISSUE TITLE
Pass LiveData<ArrayList<Book>> to BookListFragment

### ISSUE THREAD

**Issue by armiantos** [CMPUT301F20T24/Unlibrary#72]
Currently we have it set up so that the containing fragment calls `setBooksSource()` during `onCreateView`, it'd be much cleaner and less error prone if we could simply pass in a bound variable. I'm not exactly sure how to best implement this, but I found these helpful as for what we can do and what to avoid.

- [Binding adapters](https://developer.android.com/topic/libraries/data-binding/binding-adapters)
- [Binding layout to architectural components](https://developer.android.com/topic/libraries/data-binding/architecture)

**Comment by cyrusdiego** [comment]
Could we use something like `Transformations.map`? Not sure if I fully grasp the issue, but this will essentially let the view observe live data in the viewmodel which is listening to live data in the repository. [link](https://developer.android.com/reference/android/arch/lifecycle/Transformations#map(android.arch.lifecycle.LiveData<X>,%20android.arch.core.util.Function<X,%20Y>))

**Comment by armiantos** [comment]
I read into Transformations but haven't tried yet. Current patch in our case is to inject a BooksSource from the parent fragment during `onCreateView`. In the end I'd like to pass the ViewModel in xml instead of in code (if that's even possible). Unlike the other bindings, we're passing different viewmodels on different context (fragments)

**Comment by armiantos** [comment]
Marking this as out of scope
