### ISSUE TITLE
Filter library book list at the view model level

### ISSUE THREAD

**Issue by calebschoepp** [CMPUT301F20T24/Unlibrary#93]
Currently the library re-queries all the books when a filter is selected. This is inefficient. Rather, the view model should just filter which books should be displayed.

**Comment by armiantos** [comment]
So client side filtering?

**Comment by calebschoepp** [comment]
Yes, that is a much more succinct way to describe it.

**Comment by armiantos** [comment]
@calebschoepp do we still want to pursue this?

**Comment by calebschoepp** [comment]
Probably not. I think we have higher priorities

**Comment by armiantos** [comment]
Sounds good. Marking this as out of scope as well.
